### ISSUE TITLE
Windows 7 0x0000221

### ISSUE THREAD

**Issue by aiwnjoo** [katlogic/WindowsD#3]
Hi, great tool but does not seem to work correctly on Windows 7.  I think this is because only g_CiOptions is used than g_CiEnabled?

I will try test on Windows 10 and feed back.  Great tool and services.exe hook to avoid patchguard is awesome.  DSEFix bugchecks on 8.1/10 due to this issue.  Thanks

**Comment by katlogic** [comment]
Works here on win7, though I tested it only with FreeOTFE. WinD also loads its own driver via same method. Does slshim report it installed succesfuly? If so, it's own unsigned driver got loaded.

Something else might be at play. Error 0x0000221 is STATUS_IMAGE_CHECKSUM_MISMATCH - can you provide the .sys file you're trying to load (you can also privately, via kat@lua.cz)

**Comment by aiwnjoo** [comment]
Ok I tested on Windows 10 and works perfectly, 14393.

One thing I did notice is, few seconds after i run wind64 /? it comes up with an unsigned driver message for wind64.sys, then once i enter the parameter wind64 /l mydriver.sys that loads perfect.  Is that normal to get the message on your driver?

Windows 7 I have used DSEFix in the past, maybe this is causing an issue.  I will Email you binary.  Thanks

**Comment by katlogic** [comment]
The messages are just UI thing, it will appear for anything dropped into c:\windows\system32\drivers. Annoying, but can be safely ignored as those are not related to kernel.

If you happen to find out how to disable the notifications, please do tell.

Also, what error message you're getting *exactly* on win7, i still need to know if wind driver even manages to load.

**Comment by katlogic** [comment]
Was a broken driver file, WinD is fine.

**Comment by aiwnjoo** [comment]
Incorrect header issue in my driver, marking as resolved.  Thankyou.
